# Generated by Django 5.1.1 on 2024-11-01 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_alter_vehiculo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': [('visualizar_catalogo', 'Puede visualizar Catálogo de Vehículos'), ('Can_add_vehiculo_model', 'Puede agregar un vehiculo')]},
        ),
    ]
